https://test-backend-flutter.surfstudio.ru/place/1

swagger:
https://test-backend-flutter.surfstudio.ru/client/client.html#/


int id;
double lat;
double lng;
String name;
List<String> urls;
String placeType;
String description;