name: places
description: A new Flutter project.
publish_to: 'none'
version: 1.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.3
  dio: ^4.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^0.19.3
  provider: ^5.0.0
  rxdart: ^0.27.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  surf_lint_rules: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - res/
    - res/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: res/fonts/Roboto-Regular.ttf


